### PR TITLE
Renaming

### PR DESCRIPTION
**Pull request by jeffcarlin**
Apologies for the ugly PR, Simon! This is our attempt at renaming the files to be consistent throughout faro.

### CODE REVIEW

**Comment by timj** [comment]
In case you haven't noticed there is a bad merge commit on this PR that will go away if you rebase.

**Comment by bechtol** [comment]
This PR is following the renaming proposal outlined here: https://confluence.lsstcorp.org/display/DM/Metric+Calculation+Package+Reorgnization

I'll call out two topics:

(1) Currently the `__init__.py` files have many `from xxx import *` . Is this something that we want? We ran into an issue of circular imports during the refactoring and for the comment have commented out the imports in `python/lsst/faro/base/__init__.py` to avoid that behavior. Before the restructuring of the directories, all the main class definitions for the Tasks were in the same directory.

(2) Currently we have "Measurement" and "Measure" appearing in file names. "Meas" is used consistently in class names (we think). Do we want to use of these consistently throughout (or at least choose one of "Measurement" and "Measure" for file names)?

**Review by SimonKrughoff — APPROVED** [review]
This looks very good in general.  

There is only one thing I'd like to see before merging.  There is still a file called `python/lsst/faro/preparation/MatchedCatalog.py`.  I _think_ that is all contained in the `MatchedPrepTasks.py` file, so we should get rid of the former if it's really not being used for anything.

I think there are a couple more clean up things that we should try to tackle on separate tickets.  I did notice in a few places that moved files looked like a delete then a file creation.  I think using `git mv` in those cases may do a better job of figuring out when that is what's going on.

I'm suggesting doing the following on follow up organizational tickets:
* I wonder if we should have an organizational structure for the pipelines similar to what we do with the code
* We have `__init__.py` files in all but one of the code directories.  That allows import of classes by referring to the namespace i.e. `from lsst.fara.base import SomeBaseClass`, but in many places we are still referring to the file.  My recommendation is that we stop referring to the file names, but I also think we should add `__all__` attributes to all the files we import form in the `__init__.py` files.  I think this is something we could probably take care of in an hour with all hands on deck.
* We should pick "Meas" or "Measure" and use it everywhere.  This is also something I think we could just get done with a bit of time on a call.

**Comment by SimonKrughoff** [comment]
I should note that I changed the package name to `faro` as part of my fixing merge conflicts.  I think that means once we merge this all we need to do is rename the repository and we will be done with renaming.  There are some organizational questions left, but they don't involve naming or naming conventions.

**Pull request merged**
